# Find all the available rules by running:
# swiftlint rules

#included: # paths to include during linting. `--path` is ignored if present.
#  - Chamasma
#excluded: # paths to ignore during linting. Takes precedence over `included`.
#  - Carthage
#  - Pods
#  - Source/ExcludedFolder
#  - Source/ExcludedFile.swift
#  - Source/*/ExcludedFile.swift # Exclude files with a wildcard

# Default rules
blanket_disable_command:
    severity: error
block_based_kvo:
    severity: error
class_delegate_protocol:
    severity: error
closing_brace:
    severity: error
closure_parameter_position:
    severity: error
colon:
    severity: error
comma:
    severity: error
comment_spacing:
    severity: error
compiler_protocol_init:
    severity: error
computed_accessors_order:
    severity: error
control_statement:
    severity: error
#custom_rules
#cyclomatic_complexity
deployment_target:
    severity: error
discouraged_direct_init:
    severity: error
duplicate_conditions:
    severity: error
duplicate_enum_cases:
    severity: error
duplicate_imports:
    severity: error
duplicated_key_in_dictionary_literal: error
dynamic_inline:
    severity: error
empty_enum_arguments:
    severity: error
empty_parameters:
    severity: error
empty_parentheses_with_trailing_closure:
    severity: error
file_length:
    - 500
    - 1200
for_where:
    severity: error
force_cast:
    severity: error
force_try:
    severity: error
function_body_length:
    - 50
    - 100
function_parameter_count:
    warning: 5
    error: 8
    ignores_default_parameters: false
generic_type_name:
    severity: error
identifier_name:
    max_length:
        warning: 40
        error: 60
    excluded: [“^id$”]
    allowed_symbols: []
    validates_start_with_lowercase: true
implicit_getter: error
inclusive_language:
    severity: warning
    additional_terms: []
    override_terms: []
    override_allowed_terms: []
invalid_swiftlint_command:
    severity: error
is_disjoint:
    severity: error
large_tuple:
    error: 4
leading_whitespace:
    severity: error
legacy_cggeometry_functions:
    severity: error
legacy_constant:
    severity: error
legacy_constructor:
    severity: error
legacy_hashing:
    severity: error
legacy_nsgeometry_functions:
    severity: error
legacy_random:
    severity: error
line_length:
    - 110
    - 130
mark:
    severity: error
multiple_closures_with_trailing_closure:
    severity: error
nesting:
    severity: error
no_fallthrough_only:
    severity: error
no_space_in_method_call:
    severity: error
notification_center_detachment:
    severity: error
ns_number_init_as_function_reference:
    severity: error
nsobject_prefer_isequal:
    severity: error
opening_brace:
    severity: error
operator_whitespace:
    severity: error
orphaned_doc_comment:
    severity: error
private_over_fileprivate:
    severity: error
private_unit_test:
    severity: error
protocol_property_accessors_order:
    severity: error
reduce_boolean:
    severity: error
redundant_discardable_let:
    severity: error
redundant_objc_attribute:
    severity: error
redundant_optional_initialization:
    severity: error
redundant_set_access_control:
    severity: error
redundant_string_enum_value:
    severity: error
redundant_void_return:
    severity: error
return_arrow_whitespace:
    severity: error
self_in_property_initialization:
    severity: error
shorthand_operator:
    severity: error
statement_position:
    severity: error
superfluous_disable_command:
    severity: error
switch_case_alignment:
    severity: error
syntactic_sugar:
    severity: error
todo: warning
trailing_comma:
  mandatory_comma: true
  severity: error
trailing_newline:
    severity: error
trailing_semicolon:
    severity: error
trailing_whitespace:
    severity: error
type_body_length:
    - 300
    - 400
type_name:
    severity: error
unavailable_condition:
    severity: error
unneeded_break_in_switch:
    severity: error
unused_closure_parameter:
    severity: error
unused_control_flow_label:
    severity: error
unused_enumerated:
    severity: error
unused_optional_binding:
    severity: error
unused_setter_value:
    severity: error
valid_ibinspectable:
    severity: error
vertical_parameter_alignment:
    severity: error
vertical_whitespace:
    severity: error
void_function_in_ternary:
    severity: error
void_return:
    severity: error
xctfail_message:
    severity: error

#disabled_rules: # rule identifiers to exclude from running
#
opt_in_rules: # some rules are only opt-in
    - accessibility_label_for_image
    - accessibility_trait_for_button
    - anonymous_argument_in_multiline_closure
    - anyobject_protocol
    - array_init
    - attributes
    - balanced_xctest_lifecycle
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - direct_return
    - discarded_notification_center_observer
    - discouraged_assert
    - discouraged_none_name
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - expiring_todo
    - explicit_acl
    - explicit_enum_raw_value
    - explicit_init
    - explicit_top_level_acl
    - explicit_type_interface
    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    - file_header
    - file_name
    - file_name_no_space
    - file_types_order
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - function_default_parameter_at_end
    - ibinspectable_in_extension
    - identical_operands
    - implicit_return
    - implicitly_unwrapped_optional
    - indentation_width
    - inert_defer
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_objc_type
    - let_var_whitespace
    - literal_expression_end_indentation
    - local_doc_comment
    - lower_acl_than_parent
    - missing_docs
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - nimble_operator
    - no_extension_access_modifier
    - no_grouping_extension
    - no_magic_numbers
    - nslocalizedstring_key
    - nslocalizedstring_require_bundle
    - number_separator
    - object_literal
    - operator_usage_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - period_spacing
    - prefer_nimble
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - prefixed_toplevel_constant
    - private_action
    - private_outlet
    - private_subject
    - prohibited_interface_builder
    - prohibited_super_call
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    #  - raw_value_for_camel_cased_codable_enum
    - reduce_into
    - redundant_nil_coalescing
    - redundant_type_annotation
    - required_deinit
    #  - required_enum_case
    - return_value_from_void_function
    - self_binding
    - shorthand_optional_binding
    - single_test_class
    - sorted_enum_cases
    - sorted_first_last
    - sorted_imports
    - static_operator
    - strict_fileprivate
    - strong_iboutlet
    - superfluous_else
    - switch_case_on_newline
    - test_case_accessibility
    - toggle_bool
    - trailing_closure
    - type_contents_order
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_capture_list
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - weak_delegate
    - xct_specific_matcher
    - yoda_condition
    
    # Analyzer Rules
    - capture_variable: warning
    - explicit_self: warning
    - typesafe_array_init: warning
    - unused_declaration: warning
    - unused_import: warning
  
reporter: "xcode"
